services:
  
  django:
    build: .
    container_name: django
    command: [gunicorn, --bind, 0.0.0.0:8000, shopApp.wsgi]
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=swiftDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    