services:
  
  django:
    build: .
    container_name: django
    command: python service/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=swiftDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb